# mkdocs.yml - Simple Documentation Configuration

# Site Information
site_name: Django PDF Actions
site_description: A powerful Django application that adds PDF export capabilities to your Django admin interface.
site_author: Ibrahim Roshdy
site_url: https://ibrahimroshdy.github.io/django-pdf-actions/

# Copyright Information 
copyright: Copyright &copy; 2025 Ibrahim Roshdy

# Repository Information
repo_url: https://github.com/ibrahimroshdy/django-pdf-actions
repo_name: ibrahimroshdy/django-pdf-actions

# Plugins Configuration
plugins:
  - search
  - mermaid2

# Theme Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - navigation.footer
    - navigation.sections
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# Navigation Configuration
nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Quick Start: quickstart.md
      - Basic Usage: usage.md
  - Configuration:
      - Settings: settings.md
  - Examples:
      - Real-world Examples: examples.md
      - Custom Admin Methods: custom-methods.md

# Markdown Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
